"""Localized text for tool fallback paths that bypass the LLM.

These are deterministic templates (no-hits answers, "no match found" messages,
etc.) built directly in Python rather than generated by a model call, so they
can't rely on a system-prompt language directive. They pick a language from
this small table instead, keyed by the same resolved session language that
reaches the LLM-facing prompts (see backend/services/chat/language.py).

Covers the three locales the frontend supports (zh-CN/en-US/ja-JP -> Chinese/
English/Japanese); anything else falls back to English, matching the project's
default-to-English policy.
"""

from __future__ import annotations

from contextvars import ContextVar
from typing import Dict, Optional


# Single source of truth: the project's default-to-English policy lives in
# backend/services/chat/language.py (consumed by master_runtime.py to resolve
# session locale). Read it here instead of redefining a separate constant, so
# this module can't silently drift out of sync with the policy it implements.
#
# The import is deferred to first use rather than done at module level:
# backend.services.chat's __init__ eagerly imports master_runtime.py, which
# imports back from backend.services.agent.* (CrewFactory, ToolResolver, ...)
# - the very package this module lives in. Importing backend.services.chat at
# module load time, before backend.services.agent has finished initializing,
# would risk a circular import; deferring to first real call (after both
# packages are fully loaded) avoids that.
def _default_language() -> str:
    from backend.services.chat.language import DEFAULT_RESPONSE_LANGUAGE

    return DEFAULT_RESPONSE_LANGUAGE


KB_HEADERS: Dict[str, Dict[str, str]] = {
    "English": {"answer": "### Answer", "evidence": "### Evidence", "not_covered": "### Not Covered"},
    "Chinese": {"answer": "### 答案", "evidence": "### 依据", "not_covered": "### 未覆盖信息"},
    "Japanese": {"answer": "### 回答", "evidence": "### 根拠", "not_covered": "### 未カバー情報"},
}

KB_STRINGS: Dict[str, Dict[str, str]] = {
    "English": {
        "no_evidence": "Not enough evidence found in the knowledge base.",
        "none": "None",
        "found_related": "Found the following related material in the knowledge base.",
        "no_body_text": (
            "A body-level conclusion requires parseable full text in the knowledge base; the first "
            "version of archive indexing only indexes file names and paths. Question: {query}"
        ),
        "missing_query": "Please provide a knowledge base question.",
        "disabled": "Knowledge base query is currently disabled.",
    },
    "Chinese": {
        "no_evidence": "知识库未找到足够依据。",
        "none": "无",
        "found_related": "已在知识库中找到以下相关资料。",
        "no_body_text": (
            "如需正文级结论，需要知识库中存在可解析正文；压缩包第一版只索引文件名和路径。问题：{query}"
        ),
        "missing_query": "请提供要查询的知识库问题。",
        "disabled": "知识库查询当前未启用。",
    },
    "Japanese": {
        "no_evidence": "ナレッジベースに十分な根拠が見つかりませんでした。",
        "none": "なし",
        "found_related": "ナレッジベースで以下の関連資料が見つかりました。",
        "no_body_text": (
            "本文レベルの結論には、ナレッジベースに解析可能な本文が必要です。"
            "アーカイブ索引の初版はファイル名とパスのみを索引しています。質問：{query}"
        ),
        "missing_query": "ナレッジベースへの質問を入力してください。",
        "disabled": "現在、ナレッジベース検索は無効になっています。",
    },
}

# analyze_media.py's fallback instruction to the multimodal LLM when the user
# attaches media without asking a specific question. Unlike most fallback
# strings here this text becomes a directive to the model, not just a
# deterministic reply to the user - so it must itself request output in the
# resolved session language, or the model has no other language signal to
# follow (there was previously no such signal at all: this fallback always
# requested output in Chinese regardless of session locale).
MEDIA_STRINGS: Dict[str, Dict[str, str]] = {
    "English": {
        "default_question": "Describe the key points of this media content in detail, in English.",
    },
    "Chinese": {
        "default_question": "请用中文详细描述这些媒体内容的要点。",
    },
    "Japanese": {
        "default_question": "このメディアコンテンツの要点を日本語で詳しく説明してください。",
    },
}

# Citation formatting for knowledge_base_core/answer.py's _source_label(),
# used both in the LLM-facing retrieval context and in the deterministic
# evidence_only_answer() fallback shown directly to the user.
KB_CITATION_TEXT: Dict[str, Dict[str, str]] = {
    "English": {
        "file_quote_open": '"',
        "file_quote_close": '"',
        "page_label": "p. {page}",
        "citation_separator": ": ",
    },
    "Chinese": {
        "file_quote_open": "《",
        "file_quote_close": "》",
        "page_label": "页码 {page}",
        "citation_separator": "：",
    },
    "Japanese": {
        "file_quote_open": "「",
        "file_quote_close": "」",
        "page_label": "ページ {page}",
        "citation_separator": "：",
    },
}

HR_STRINGS: Dict[str, Dict[str, str]] = {
    "English": {
        "no_matching_people": "No matching employees found.",
        "no_matching_employee_guidance": "No matching employee found; please provide a clearer name or employee ID.",
        "missing_query": "Please provide an HR business question, or pass a query_spec JSON.",
    },
    "Chinese": {
        "no_matching_people": "未找到匹配人员。",
        "no_matching_employee_guidance": "未找到匹配员工；请提供更明确的姓名或员工 ID。",
        "missing_query": "请提供一个 HR 业务问题，或传入 query_spec JSON。",
    },
    "Japanese": {
        "no_matching_people": "該当する社員が見つかりませんでした。",
        "no_matching_employee_guidance": "該当する社員が見つかりませんでした。氏名または社員IDをより明確にご指定ください。",
        "missing_query": "HR業務に関する質問を入力するか、query_spec の JSON を渡してください。",
    },
}


HR_FIELD_LABELS: Dict[str, Dict[str, str]] = {
    "English": {
        "employee_id": "Employee ID",
        "name": "Name",
        "office_city": "Office Location",
        "email": "Email",
        "department_code": "Department Code",
        "department_name": "Department",
        "job_title": "Job Title",
        "manager_id": "Manager",
        "hire_date": "Hire Date",
        "tenure_years": "Tenure",
        "employment_status": "Status",
        "attrition_risk": "Attrition Risk",
        "grade": "Grade",
    },
    "Chinese": {
        "employee_id": "工号",
        "name": "姓名",
        "office_city": "办公地点",
        "email": "邮箱",
        "department_code": "部门编码",
        "department_name": "部门",
        "job_title": "职位",
        "manager_id": "经理",
        "hire_date": "入职日期",
        "tenure_years": "入职年限",
        "employment_status": "状态",
        "attrition_risk": "离职风险",
        "grade": "职级",
    },
    "Japanese": {
        "employee_id": "社員ID",
        "name": "氏名",
        "office_city": "勤務地",
        "email": "メール",
        "department_code": "部門コード",
        "department_name": "部門",
        "job_title": "役職",
        "manager_id": "マネージャー",
        "hire_date": "入社日",
        "tenure_years": "勤続年数",
        "employment_status": "在籍状況",
        "attrition_risk": "離職リスク",
        "grade": "グレード",
    },
}

# office_city gets a distinct label ("office city" vs "office location") when it
# appears alongside other attributes in a multi-field summary sentence.
HR_ATTRIBUTE_LABEL_OVERRIDES: Dict[str, Dict[str, str]] = {
    "English": {"office_city": "Office City"},
    "Chinese": {"office_city": "办公城市"},
    "Japanese": {"office_city": "勤務都市"},
}

HR_ATTRIBUTE_TEXT: Dict[str, Dict[str, str]] = {
    "English": {
        "unfilled": "Not filled in",
        "active": "Active",
        "inactive": "Inactive",
        "tenure_years": "About {value:.1f} years",
        "list_separator": ", ",
        "unnamed_subject": "This employee",
        "attribute_sentence": "{subject}'s {label} is {value}.",
        "attribute_summary": "{subject}'s info: {pairs}.",
        "attribute_pair_separator": ": ",
        "attribute_pair_joiner": "; ",
        "tenure_note": ", tenure {value}",
        "detail_header": "- {name} ({employee_id}):",
        "detail_line": "  - {label}: {value}",
        "detail_manager_id_label": "Manager ID",
        "detail_found_header": "Found {total} matching employees:",
        "person_summary": "{name} ({employee_id}, {department_code}, {grade}, {job_title}, {office_city}, {status})",
        "status_unknown": "Status unavailable",
        "none_bullet": "- None",
        "direct_reports_note": ", direct reports: {count}",
    },
    "Chinese": {
        "unfilled": "未填",
        "active": "在职",
        "inactive": "非在职",
        "tenure_years": "约 {value:.1f} 年",
        "list_separator": "、",
        "unnamed_subject": "该员工",
        "attribute_sentence": "{subject}的{label}是{value}。",
        "attribute_summary": "{subject}的信息：{pairs}。",
        "attribute_pair_separator": "：",
        "attribute_pair_joiner": "；",
        "tenure_note": "，入职年限{value}",
        "detail_header": "- {name}（{employee_id}）：",
        "detail_line": "  - {label}：{value}",
        "detail_manager_id_label": "经理 ID",
        "detail_found_header": "找到 {total} 名匹配人员：",
        "person_summary": "{name}（{employee_id}，{department_code}，{grade}，{job_title}，{office_city}，{status}）",
        "status_unknown": "状态未返回",
        "none_bullet": "- 无",
        "direct_reports_note": "，直接下属 {count} 人",
    },
    "Japanese": {
        "unfilled": "未入力",
        "active": "在籍",
        "inactive": "非在籍",
        "tenure_years": "約 {value:.1f} 年",
        "list_separator": "、",
        "unnamed_subject": "この社員",
        "attribute_sentence": "{subject}の{label}は{value}です。",
        "attribute_summary": "{subject}の情報：{pairs}。",
        "attribute_pair_separator": "：",
        "attribute_pair_joiner": "；",
        "tenure_note": "、勤続年数{value}",
        "detail_header": "- {name}（{employee_id}）：",
        "detail_line": "  - {label}：{value}",
        "detail_manager_id_label": "マネージャーID",
        "detail_found_header": "該当する社員が{total}名見つかりました：",
        "person_summary": "{name}（{employee_id}、{department_code}、{grade}、{job_title}、{office_city}、{status}）",
        "status_unknown": "在籍状況不明",
        "none_bullet": "- なし",
        "direct_reports_note": "、直属部下 {count} 名",
    },
}


def hr_field_label(field: str, language: Optional[str]) -> str:
    table = HR_FIELD_LABELS.get(language or "", HR_FIELD_LABELS[_default_language()])
    return table.get(field, field)


def hr_attribute_label(field: str, language: Optional[str]) -> str:
    overrides = HR_ATTRIBUTE_LABEL_OVERRIDES.get(
        language or "", HR_ATTRIBUTE_LABEL_OVERRIDES[_default_language()]
    )
    if field in overrides:
        return overrides[field]
    return hr_field_label(field, language)


def hr_attribute_text(key: str, language: Optional[str]) -> str:
    default = _default_language()
    table = HR_ATTRIBUTE_TEXT.get(language or "", HR_ATTRIBUTE_TEXT[default])
    return table.get(key, HR_ATTRIBUTE_TEXT[default][key])


# Whole-line/whole-sentence templates for the HR sample-backend and ES-mirror
# report functions in business_query_core/hr/executor.py (section headers,
# per-row lines, and one-off messages). Kept separate from HR_ATTRIBUTE_TEXT,
# which holds word/phrase-level fragments (labels, status words, separators)
# reused across many of these templates.
HR_MESSAGES: Dict[str, Dict[str, str]] = {
    "English": {
        "most_reports_line": (
            "The employee with the most direct reports is {manager_name} ({manager_id}), "
            "with {count} active direct reports."
        ),
        "cross_timezone_header": "Cross-timezone reporting relationships:",
        "cross_timezone_none": "No cross-timezone reporting found.",
        "cross_timezone_line": "- {name} ({from_tz}) -> {manager_name} ({manager_tz})",
        "manager_reports_line": "{label} ({manager_id}) has {count} active direct reports.",
        "no_manager_header": "There are {count} employees with no manager specified:",
        "invalid_manager_header": "Records with a nonexistent manager ID: {count}.",
        "invalid_email_header": "Records with malformed email addresses: {count}.",
        "duplicate_id_header": "Duplicate employee IDs: {count}.",
        "duplicate_id_note": (
            "- No duplicate employee IDs found in the sample primary index; production should "
            "detect these at the raw-data layer."
        ),
        "duplicate_id_es_note": (
            "Duplicate employee IDs: the primary employee index uses `_id=employee_id`, so "
            "duplicates get overwritten; detect these in the raw JSONL or the original data layer instead."
        ),
        "fte_hours_conflict_header": "Records with FTE 0.5 but standard hours 40: {count}.",
        "missing_fields_header": "Records missing key fields (department, grade): {count}.",
        "resume_summary_found_header": "Found {count} resume summaries:",
        "resume_summary_line": "- {name} ({employee_id}): {summary}",
        "resume_material_found_header": "Found {count} resume records:",
        "no_identified_person": (
            "No specific person identified; try entering a name or employee ID, or filter the "
            "employee list first."
        ),
        "no_resume_summary": "No resume summary",
        "no_mock_link": "No mock link",
        "resume_line": "- {name} ({employee_id}): {summary}; asset: {storage_uri}",
        "distribution_header": "Matched {count} employees; distribution by `{field}`:",
        "distribution_line": "- {key}: {count} ({ratio:.1f}%)",
        "avg_tenure_line": "Matched {count} active employees; average tenure is about {avg:.1f} years.",
        "matched_total_line": "Matched {count} employees total.",
        "filtered_note": "Counted using the filters from QuerySpec.",
        "married_ratio_line": "{count} married employees, {ratio:.1f}% of all employees.",
        "pay_scale_fte_header": "Average FTE by pay scale grade:",
        "pay_scale_fte_line": "- {key}: average FTE {avg:.2f}, sample size {count}",
        "standard_hours_ratio_line": "{count} employees have standard hours of 40, {ratio:.1f}% of all employees.",
        "matched_returned_line": "Matched {total} employees total; showing the first {n}:",
        "aggregation_header_with_total": "Matched {total} employees total; aggregation results:",
        "aggregation_bucket_line": "  - {key}: {count}",
        "aggregation_field_header": "- {name}:",
        "aggregation_value_line": "- {name}: {value}",
        "please_specify_field": (
            "Please specify which employee field to query, e.g. office location, employee ID, "
            "email, or department."
        ),
        "clarify_query": "Please provide more query details.",
        "retired_terminated_header": "Retired or terminated employees: {count} total:",
        "manager_grade_header": "Manager-grade employees with more than 3 direct reports: {count} total:",
        "tenure_sort_header": "Filtered by {label} tenure; matched {count} employees total, showing the first {n}:",
        "tenure_label_longest": "longest",
        "tenure_label_shortest": "shortest",
        "tenure_threshold_header": (
            "Employees with more than {threshold:g} years of tenure meeting the criteria: {count} total:"
        ),
        "city_comparison_header": "Reporting-relationship comparison between {city1} and {city2}:",
        "city_comparison_line": (
            "- {city}: {count} employees, {managers} direct managers involved, {cross} cross-city reports."
        ),
        "results_title": "### HR Query Results",
        "notes_header": "### Notes",
        "note_es_backend": "- The current production entry point runs controlled query plans against the Elasticsearch HR index.",
        "note_unified_planner": (
            "- The unified planner produces QueryIR, ES DSL, or an internal QuerySpec; the executor only "
            "consumes validated, controlled structures."
        ),
        "note_placeholder_checks": "- Permission checks and query cost control are still first-phase placeholders.",
        "matched_people_header": "### Matched Employees",
        "more_not_shown": "- {count} more not shown.",
        "query_plan_header": "### Query Plan & Validation",
        "error_title": "### HR Query Could Not Be Executed",
        "queryspec_validation_failed": "QuerySpec validation failed: {error}",
        "execution_failed": "HR query execution failed: {error_type}: {error}",
        "data_quality_boundary_message": (
            "This is an HR data quality/data governance check, not an employee business query. Please use an "
            "admin or data governance tool instead, such as the standalone `hr_data_quality_query`, a data "
            "inspection job, or the data governance backend."
        ),
        "unsupported_fields_header": "### Unsupported Fields",
        "no_education_field_note": (
            "The current HR employee index does not provide education/degree/school fields, so this system "
            "cannot answer that directly."
        ),
    },
    "Chinese": {
        "most_reports_line": "直接下属最多的是 {manager_name}（{manager_id}），共有 {count} 名在职直接下属。",
        "cross_timezone_header": "跨时区汇报情况如下：",
        "cross_timezone_none": "未发现跨时区汇报。",
        "cross_timezone_line": "- {name}（{from_tz}） -> {manager_name}（{manager_tz}）",
        "manager_reports_line": "{label}（{manager_id}）共有 {count} 名在职直接下属。",
        "no_manager_header": "没有指定经理的员工共有 {count} 名：",
        "invalid_manager_header": "经理 ID 不存在的记录：{count} 条。",
        "invalid_email_header": "邮箱格式异常的记录：{count} 条。",
        "duplicate_id_header": "重复员工 ID：{count} 个。",
        "duplicate_id_note": "- 样例主索引中未发现重复员工 ID；真实场景应在原始数据层检测。",
        "duplicate_id_es_note": "重复员工 ID：主员工索引用 `_id=employee_id` 会覆盖重复；请在 raw JSONL 或原始数据层检测。",
        "fte_hours_conflict_header": "FTE 为 0.5 但标准工时为 40 的记录：{count} 条。",
        "missing_fields_header": "缺失关键字段（部门、职级）的记录：{count} 条。",
        "resume_summary_found_header": "找到 {count} 份简历摘要：",
        "resume_summary_line": "- {name}（{employee_id}）：{summary}",
        "resume_material_found_header": "找到 {count} 份简历资料：",
        "no_identified_person": "未识别到明确人员；可尝试输入姓名、员工 ID，或先筛选人员列表。",
        "no_resume_summary": "无简历摘要",
        "no_mock_link": "无模拟链接",
        "resume_line": "- {name}（{employee_id}）：{summary}；资产：{storage_uri}",
        "distribution_header": "匹配员工共 {count} 人，按 `{field}` 分布如下：",
        "distribution_line": "- {key}：{count} 人（{ratio:.1f}%）",
        "avg_tenure_line": "匹配在职员工 {count} 人，平均司龄约 {avg:.1f} 年。",
        "matched_total_line": "匹配员工共 {count} 人。",
        "filtered_note": "已按 QuerySpec 中的过滤条件统计。",
        "married_ratio_line": "已婚员工 {count} 人，占全部员工 {ratio:.1f}%。",
        "pay_scale_fte_header": "各薪酬等级的平均 FTE 如下：",
        "pay_scale_fte_line": "- {key}：平均 FTE {avg:.2f}，样本 {count} 人",
        "standard_hours_ratio_line": "标准工时为 40 小时的员工 {count} 人，占全部员工 {ratio:.1f}%。",
        "matched_returned_line": "匹配员工共 {total} 人，返回前 {n} 人：",
        "aggregation_header_with_total": "匹配员工共 {total} 人，聚合结果如下：",
        "aggregation_bucket_line": "  - {key}：{count} 人",
        "aggregation_field_header": "- {name}：",
        "aggregation_value_line": "- {name}：{value}",
        "please_specify_field": "请说明要查询员工的哪个字段，例如办公地点、工号、邮箱或部门。",
        "clarify_query": "请补充查询条件。",
        "retired_terminated_header": "已退休或已解雇/离职人员共 {count} 人：",
        "manager_grade_header": "经理级且直接下属 > 3 人的员工共 {count} 人：",
        "tenure_sort_header": "按入职年限{label}筛选，匹配员工共 {count} 人，返回前 {n} 人：",
        "tenure_label_longest": "最长",
        "tenure_label_shortest": "最短",
        "tenure_threshold_header": "入职超过 {threshold:g} 年且满足条件的员工共 {count} 人：",
        "city_comparison_header": "{city1}和{city2}两地人员汇报关系对比：",
        "city_comparison_line": "- {city}：员工 {count} 人，涉及直属经理 {managers} 位，跨城市汇报 {cross} 人。",
        "results_title": "### HR 查询结果",
        "notes_header": "### 说明",
        "note_es_backend": "- 当前生产入口使用 Elasticsearch HR 索引执行受控查询计划。",
        "note_unified_planner": "- 统一规划器生成 QueryIR、ES DSL 或内部 QuerySpec；执行器只消费通过校验的受控结构。",
        "note_placeholder_checks": "- 权限校验与查询成本控制仍为第一阶段占位。",
        "matched_people_header": "### 匹配人员",
        "more_not_shown": "- 另有 {count} 条未展示。",
        "query_plan_header": "### 查询计划与校验",
        "error_title": "### HR 查询无法执行",
        "queryspec_validation_failed": "QuerySpec 校验失败：{error}",
        "execution_failed": "HR 查询执行失败：{error_type}: {error}",
        "data_quality_boundary_message": (
            "这是 HR 数据质量/数据治理检查问题，不属于员工业务查询入口。请使用管理员或数据治理工具处理，"
            "例如独立的 `hr_data_quality_query`、数据巡检任务或数据治理后台。"
        ),
        "unsupported_fields_header": "### 未覆盖字段",
        "no_education_field_note": "当前 HR 员工索引未提供学历/学位/毕业院校字段，因此无法从本系统直接查询该信息。",
    },
    "Japanese": {
        "most_reports_line": "直属部下が最も多いのは{manager_name}（{manager_id}）で、在籍中の直属部下は{count}名です。",
        "cross_timezone_header": "タイムゾーンをまたぐ報告関係は以下の通りです：",
        "cross_timezone_none": "タイムゾーンをまたぐ報告関係は見つかりませんでした。",
        "cross_timezone_line": "- {name}（{from_tz}） -> {manager_name}（{manager_tz}）",
        "manager_reports_line": "{label}（{manager_id}）には在籍中の直属部下が{count}名います。",
        "no_manager_header": "経理が指定されていない社員は{count}名です：",
        "invalid_manager_header": "存在しないマネージャーIDのレコード：{count}件。",
        "invalid_email_header": "メール形式が不正なレコード：{count}件。",
        "duplicate_id_header": "重複した社員ID：{count}件。",
        "duplicate_id_note": "- サンプルの主インデックスでは重複した社員IDは見つかりませんでした。実運用では生データ層で検出してください。",
        "duplicate_id_es_note": "重複した社員ID：主インデックスは `_id=employee_id` を使用しているため重複は上書きされます。raw JSONL または元データ層で検出してください。",
        "fte_hours_conflict_header": "FTEが0.5なのに標準労働時間が40のレコード：{count}件。",
        "missing_fields_header": "重要フィールド（部門、グレード）が欠落しているレコード：{count}件。",
        "resume_summary_found_header": "{count}件の履歴書要約が見つかりました：",
        "resume_summary_line": "- {name}（{employee_id}）：{summary}",
        "resume_material_found_header": "{count}件の履歴書資料が見つかりました：",
        "no_identified_person": "対象となる社員を特定できませんでした。氏名や社員IDを入力するか、先に社員リストを絞り込んでください。",
        "no_resume_summary": "履歴書要約なし",
        "no_mock_link": "モックリンクなし",
        "resume_line": "- {name}（{employee_id}）：{summary}；資産：{storage_uri}",
        "distribution_header": "該当する社員は{count}名です。`{field}`別の分布は以下の通りです：",
        "distribution_line": "- {key}：{count}名（{ratio:.1f}%）",
        "avg_tenure_line": "該当する在籍社員は{count}名で、平均勤続年数は約{avg:.1f}年です。",
        "matched_total_line": "該当する社員は合計{count}名です。",
        "filtered_note": "QuerySpec のフィルタ条件で集計済みです。",
        "married_ratio_line": "既婚社員は{count}名で、全社員の{ratio:.1f}%です。",
        "pay_scale_fte_header": "各給与等級の平均FTEは以下の通りです：",
        "pay_scale_fte_line": "- {key}：平均FTE {avg:.2f}、サンプル数{count}名",
        "standard_hours_ratio_line": "標準労働時間が40時間の社員は{count}名で、全社員の{ratio:.1f}%です。",
        "matched_returned_line": "該当する社員は合計{total}名です。先頭{n}名を表示します：",
        "aggregation_header_with_total": "該当する社員は合計{total}名です。集計結果は以下の通りです：",
        "aggregation_bucket_line": "  - {key}：{count}名",
        "aggregation_field_header": "- {name}：",
        "aggregation_value_line": "- {name}：{value}",
        "please_specify_field": "問い合わせたい社員のフィールドを指定してください（例：勤務地、社員ID、メール、部門など）。",
        "clarify_query": "検索条件を補足してください。",
        "retired_terminated_header": "退職・解雇済みの社員は合計{count}名です：",
        "manager_grade_header": "マネージャー職級かつ直属部下が3名を超える社員は合計{count}名です：",
        "tenure_sort_header": "在職期間が{label}の順にフィルタしました。該当する社員は合計{count}名で、先頭{n}名を表示します：",
        "tenure_label_longest": "最長",
        "tenure_label_shortest": "最短",
        "tenure_threshold_header": "在職期間が{threshold:g}年を超え、条件を満たす社員は合計{count}名です：",
        "city_comparison_header": "{city1}と{city2}の間の報告関係比較：",
        "city_comparison_line": "- {city}：社員{count}名、関係する直属マネージャー{managers}名、都市をまたぐ報告{cross}名。",
        "results_title": "### HR照会結果",
        "notes_header": "### 補足",
        "note_es_backend": "- 現在の本番エントリーポイントは、Elasticsearch の HR インデックスに対して制御されたクエリプランを実行します。",
        "note_unified_planner": (
            "- 統合プランナーが QueryIR、ES DSL、または内部 QuerySpec を生成し、実行器は検証済みの制御された構造のみを受け付けます。"
        ),
        "note_placeholder_checks": "- 権限チェックとクエリコスト制御は、現時点では第一段階のプレースホルダーです。",
        "matched_people_header": "### 該当社員",
        "more_not_shown": "- 他{count}件は表示していません。",
        "query_plan_header": "### クエリプランと検証",
        "error_title": "### HR照会を実行できませんでした",
        "queryspec_validation_failed": "QuerySpec の検証に失敗しました：{error}",
        "execution_failed": "HR照会の実行に失敗しました：{error_type}: {error}",
        "data_quality_boundary_message": (
            "これはHRデータ品質・データガバナンスのチェックであり、社員業務照会の入口ではありません。"
            "管理者用ツールまたはデータガバナンスツール（例：独立した `hr_data_quality_query`、"
            "データ点検ジョブ、データガバナンス基盤）をご利用ください。"
        ),
        "unsupported_fields_header": "### 未対応フィールド",
        "no_education_field_note": (
            "現在のHR社員インデックスには学歴・学位・出身校のフィールドがないため、"
            "本システムから直接この情報を照会することはできません。"
        ),
    },
}


def hr_message(key: str, language: Optional[str]) -> str:
    table = HR_MESSAGES.get(language or "", HR_MESSAGES[_default_language()])
    return table.get(key, HR_MESSAGES[_default_language()][key])


def kb_headers(language: Optional[str]) -> Dict[str, str]:
    return KB_HEADERS.get(language or "", KB_HEADERS[_default_language()])


def kb_string(key: str, language: Optional[str]) -> str:
    table = KB_STRINGS.get(language or "", KB_STRINGS[_default_language()])
    return table.get(key, KB_STRINGS[_default_language()][key])


def media_string(key: str, language: Optional[str]) -> str:
    table = MEDIA_STRINGS.get(language or "", MEDIA_STRINGS[_default_language()])
    return table.get(key, MEDIA_STRINGS[_default_language()][key])


def kb_citation_text(key: str, language: Optional[str]) -> str:
    table = KB_CITATION_TEXT.get(language or "", KB_CITATION_TEXT[_default_language()])
    return table.get(key, KB_CITATION_TEXT[_default_language()][key])


def hr_string(key: str, language: Optional[str]) -> str:
    table = HR_STRINGS.get(language or "", HR_STRINGS[_default_language()])
    return table.get(key, HR_STRINGS[_default_language()][key])


# HR executor's deterministic formatting (backend/services/agent/tools/builtin/
# business_query_core/hr/executor.py) is called many levels deep from
# run_hr_business_query() without a `language` parameter threaded through
# every function. A request-scoped ContextVar avoids a large, error-prone
# signature change across that call graph; run_hr_business_query() sets it
# once per call and resets it in a `finally`.
_hr_language_ctx: ContextVar[Optional[str]] = ContextVar("hr_fallback_language", default=None)


def set_hr_language(language: Optional[str]):
    return _hr_language_ctx.set(language)


def reset_hr_language(token) -> None:
    _hr_language_ctx.reset(token)


def current_hr_language() -> str:
    return _hr_language_ctx.get() or _default_language()
