"""Localized text for tool fallback paths that bypass the LLM.

These are deterministic templates (no-hits answers, "no match found" messages,
etc.) built directly in Python rather than generated by a model call, so they
can't rely on a system-prompt language directive. They pick a language from
this small table instead, keyed by the same resolved session language that
reaches the LLM-facing prompts (see backend/services/chat/language.py).

Covers the three locales the frontend supports (zh-CN/en-US/ja-JP -> Chinese/
English/Japanese); anything else falls back to English, matching the project's
default-to-English policy.
"""

from __future__ import annotations

from contextvars import ContextVar
from typing import Dict, Optional

DEFAULT_LANGUAGE = "English"

KB_HEADERS: Dict[str, Dict[str, str]] = {
    "English": {"answer": "### Answer", "evidence": "### Evidence", "not_covered": "### Not Covered"},
    "Chinese": {"answer": "### 答案", "evidence": "### 依据", "not_covered": "### 未覆盖信息"},
    "Japanese": {"answer": "### 回答", "evidence": "### 根拠", "not_covered": "### 未カバー情報"},
}

KB_STRINGS: Dict[str, Dict[str, str]] = {
    "English": {
        "no_evidence": "Not enough evidence found in the knowledge base.",
        "none": "None",
        "found_related": "Found the following related material in the knowledge base.",
        "no_body_text": (
            "A body-level conclusion requires parseable full text in the knowledge base; the first "
            "version of archive indexing only indexes file names and paths. Question: {query}"
        ),
        "missing_query": "Please provide a knowledge base question.",
        "disabled": "Knowledge base query is currently disabled.",
    },
    "Chinese": {
        "no_evidence": "知识库未找到足够依据。",
        "none": "无",
        "found_related": "已在知识库中找到以下相关资料。",
        "no_body_text": (
            "如需正文级结论，需要知识库中存在可解析正文；压缩包第一版只索引文件名和路径。问题：{query}"
        ),
        "missing_query": "请提供要查询的知识库问题。",
        "disabled": "知识库查询当前未启用。",
    },
    "Japanese": {
        "no_evidence": "ナレッジベースに十分な根拠が見つかりませんでした。",
        "none": "なし",
        "found_related": "ナレッジベースで以下の関連資料が見つかりました。",
        "no_body_text": (
            "本文レベルの結論には、ナレッジベースに解析可能な本文が必要です。"
            "アーカイブ索引の初版はファイル名とパスのみを索引しています。質問：{query}"
        ),
        "missing_query": "ナレッジベースへの質問を入力してください。",
        "disabled": "現在、ナレッジベース検索は無効になっています。",
    },
}

# Citation formatting for knowledge_base_core/answer.py's _source_label(),
# used both in the LLM-facing retrieval context and in the deterministic
# evidence_only_answer() fallback shown directly to the user.
KB_CITATION_TEXT: Dict[str, Dict[str, str]] = {
    "English": {
        "file_quote_open": '"',
        "file_quote_close": '"',
        "page_label": "p. {page}",
        "citation_separator": ": ",
    },
    "Chinese": {
        "file_quote_open": "《",
        "file_quote_close": "》",
        "page_label": "页码 {page}",
        "citation_separator": "：",
    },
    "Japanese": {
        "file_quote_open": "「",
        "file_quote_close": "」",
        "page_label": "ページ {page}",
        "citation_separator": "：",
    },
}

HR_STRINGS: Dict[str, Dict[str, str]] = {
    "English": {
        "no_matching_people": "No matching employees found.",
        "no_matching_employee_guidance": "No matching employee found; please provide a clearer name or employee ID.",
        "missing_query": "Please provide an HR business question, or pass a query_spec JSON.",
    },
    "Chinese": {
        "no_matching_people": "未找到匹配人员。",
        "no_matching_employee_guidance": "未找到匹配员工；请提供更明确的姓名或员工 ID。",
        "missing_query": "请提供一个 HR 业务问题，或传入 query_spec JSON。",
    },
    "Japanese": {
        "no_matching_people": "該当する社員が見つかりませんでした。",
        "no_matching_employee_guidance": "該当する社員が見つかりませんでした。氏名または社員IDをより明確にご指定ください。",
        "missing_query": "HR業務に関する質問を入力するか、query_spec の JSON を渡してください。",
    },
}


HR_FIELD_LABELS: Dict[str, Dict[str, str]] = {
    "English": {
        "employee_id": "Employee ID",
        "name": "Name",
        "office_city": "Office Location",
        "email": "Email",
        "department_code": "Department Code",
        "department_name": "Department",
        "job_title": "Job Title",
        "manager_id": "Manager",
        "hire_date": "Hire Date",
        "tenure_years": "Tenure",
        "employment_status": "Status",
        "attrition_risk": "Attrition Risk",
        "grade": "Grade",
    },
    "Chinese": {
        "employee_id": "工号",
        "name": "姓名",
        "office_city": "办公地点",
        "email": "邮箱",
        "department_code": "部门编码",
        "department_name": "部门",
        "job_title": "职位",
        "manager_id": "经理",
        "hire_date": "入职日期",
        "tenure_years": "入职年限",
        "employment_status": "状态",
        "attrition_risk": "离职风险",
        "grade": "职级",
    },
    "Japanese": {
        "employee_id": "社員ID",
        "name": "氏名",
        "office_city": "勤務地",
        "email": "メール",
        "department_code": "部門コード",
        "department_name": "部門",
        "job_title": "役職",
        "manager_id": "マネージャー",
        "hire_date": "入社日",
        "tenure_years": "勤続年数",
        "employment_status": "在籍状況",
        "attrition_risk": "離職リスク",
        "grade": "グレード",
    },
}

# office_city gets a distinct label ("office city" vs "office location") when it
# appears alongside other attributes in a multi-field summary sentence.
HR_ATTRIBUTE_LABEL_OVERRIDES: Dict[str, Dict[str, str]] = {
    "English": {"office_city": "Office City"},
    "Chinese": {"office_city": "办公城市"},
    "Japanese": {"office_city": "勤務都市"},
}

HR_ATTRIBUTE_TEXT: Dict[str, Dict[str, str]] = {
    "English": {
        "unfilled": "Not filled in",
        "active": "Active",
        "inactive": "Inactive",
        "tenure_years": "About {value:.1f} years",
        "list_separator": ", ",
        "unnamed_subject": "This employee",
        "attribute_sentence": "{subject}'s {label} is {value}.",
        "attribute_summary": "{subject}'s info: {pairs}.",
        "attribute_pair_separator": ": ",
        "attribute_pair_joiner": "; ",
        "tenure_note": ", tenure {value}",
        "detail_header": "- {name} ({employee_id}):",
        "detail_line": "  - {label}: {value}",
        "detail_manager_id_label": "Manager ID",
        "detail_found_header": "Found {total} matching employees:",
    },
    "Chinese": {
        "unfilled": "未填",
        "active": "在职",
        "inactive": "非在职",
        "tenure_years": "约 {value:.1f} 年",
        "list_separator": "、",
        "unnamed_subject": "该员工",
        "attribute_sentence": "{subject}的{label}是{value}。",
        "attribute_summary": "{subject}的信息：{pairs}。",
        "attribute_pair_separator": "：",
        "attribute_pair_joiner": "；",
        "tenure_note": "，入职年限{value}",
        "detail_header": "- {name}（{employee_id}）：",
        "detail_line": "  - {label}：{value}",
        "detail_manager_id_label": "经理 ID",
        "detail_found_header": "找到 {total} 名匹配人员：",
    },
    "Japanese": {
        "unfilled": "未入力",
        "active": "在籍",
        "inactive": "非在籍",
        "tenure_years": "約 {value:.1f} 年",
        "list_separator": "、",
        "unnamed_subject": "この社員",
        "attribute_sentence": "{subject}の{label}は{value}です。",
        "attribute_summary": "{subject}の情報：{pairs}。",
        "attribute_pair_separator": "：",
        "attribute_pair_joiner": "；",
        "tenure_note": "、勤続年数{value}",
        "detail_header": "- {name}（{employee_id}）：",
        "detail_line": "  - {label}：{value}",
        "detail_manager_id_label": "マネージャーID",
        "detail_found_header": "該当する社員が{total}名見つかりました：",
    },
}


def hr_field_label(field: str, language: Optional[str]) -> str:
    table = HR_FIELD_LABELS.get(language or "", HR_FIELD_LABELS[DEFAULT_LANGUAGE])
    return table.get(field, field)


def hr_attribute_label(field: str, language: Optional[str]) -> str:
    overrides = HR_ATTRIBUTE_LABEL_OVERRIDES.get(language or "", HR_ATTRIBUTE_LABEL_OVERRIDES[DEFAULT_LANGUAGE])
    if field in overrides:
        return overrides[field]
    return hr_field_label(field, language)


def hr_attribute_text(key: str, language: Optional[str]) -> str:
    table = HR_ATTRIBUTE_TEXT.get(language or "", HR_ATTRIBUTE_TEXT[DEFAULT_LANGUAGE])
    return table.get(key, HR_ATTRIBUTE_TEXT[DEFAULT_LANGUAGE][key])


def kb_headers(language: Optional[str]) -> Dict[str, str]:
    return KB_HEADERS.get(language or "", KB_HEADERS[DEFAULT_LANGUAGE])


def kb_string(key: str, language: Optional[str]) -> str:
    table = KB_STRINGS.get(language or "", KB_STRINGS[DEFAULT_LANGUAGE])
    return table.get(key, KB_STRINGS[DEFAULT_LANGUAGE][key])


def kb_citation_text(key: str, language: Optional[str]) -> str:
    table = KB_CITATION_TEXT.get(language or "", KB_CITATION_TEXT[DEFAULT_LANGUAGE])
    return table.get(key, KB_CITATION_TEXT[DEFAULT_LANGUAGE][key])


def hr_string(key: str, language: Optional[str]) -> str:
    table = HR_STRINGS.get(language or "", HR_STRINGS[DEFAULT_LANGUAGE])
    return table.get(key, HR_STRINGS[DEFAULT_LANGUAGE][key])


# HR executor's deterministic formatting (backend/services/agent/tools/builtin/
# business_query_core/hr/executor.py) is called many levels deep from
# run_hr_business_query() without a `language` parameter threaded through
# every function. A request-scoped ContextVar avoids a large, error-prone
# signature change across that call graph; run_hr_business_query() sets it
# once per call and resets it in a `finally`.
_hr_language_ctx: ContextVar[Optional[str]] = ContextVar("hr_fallback_language", default=None)


def set_hr_language(language: Optional[str]):
    return _hr_language_ctx.set(language)


def reset_hr_language(token) -> None:
    _hr_language_ctx.reset(token)


def current_hr_language() -> str:
    return _hr_language_ctx.get() or DEFAULT_LANGUAGE
