"""Localized text for tool fallback paths that bypass the LLM.

These are deterministic templates (no-hits answers, "no match found" messages,
etc.) built directly in Python rather than generated by a model call, so they
can't rely on a system-prompt language directive. They pick a language from
this small table instead, keyed by the same resolved session language that
reaches the LLM-facing prompts (see backend/services/chat/language.py).

Covers the three locales the frontend supports (zh-CN/en-US/ja-JP -> Chinese/
English/Japanese); anything else falls back to English, matching the project's
default-to-English policy.
"""

from __future__ import annotations

from contextvars import ContextVar
from typing import Dict, Optional

DEFAULT_LANGUAGE = "English"

KB_HEADERS: Dict[str, Dict[str, str]] = {
    "English": {"answer": "### Answer", "evidence": "### Evidence", "not_covered": "### Not Covered"},
    "Chinese": {"answer": "### 答案", "evidence": "### 依据", "not_covered": "### 未覆盖信息"},
    "Japanese": {"answer": "### 回答", "evidence": "### 根拠", "not_covered": "### 未カバー情報"},
}

KB_STRINGS: Dict[str, Dict[str, str]] = {
    "English": {
        "no_evidence": "Not enough evidence found in the knowledge base.",
        "none": "None",
        "found_related": "Found the following related material in the knowledge base.",
        "no_body_text": (
            "A body-level conclusion requires parseable full text in the knowledge base; the first "
            "version of archive indexing only indexes file names and paths. Question: {query}"
        ),
        "missing_query": "Please provide a knowledge base question.",
        "disabled": "Knowledge base query is currently disabled.",
    },
    "Chinese": {
        "no_evidence": "知识库未找到足够依据。",
        "none": "无",
        "found_related": "已在知识库中找到以下相关资料。",
        "no_body_text": (
            "如需正文级结论，需要知识库中存在可解析正文；压缩包第一版只索引文件名和路径。问题：{query}"
        ),
        "missing_query": "请提供要查询的知识库问题。",
        "disabled": "知识库查询当前未启用。",
    },
    "Japanese": {
        "no_evidence": "ナレッジベースに十分な根拠が見つかりませんでした。",
        "none": "なし",
        "found_related": "ナレッジベースで以下の関連資料が見つかりました。",
        "no_body_text": (
            "本文レベルの結論には、ナレッジベースに解析可能な本文が必要です。"
            "アーカイブ索引の初版はファイル名とパスのみを索引しています。質問：{query}"
        ),
        "missing_query": "ナレッジベースへの質問を入力してください。",
        "disabled": "現在、ナレッジベース検索は無効になっています。",
    },
}

HR_STRINGS: Dict[str, Dict[str, str]] = {
    "English": {
        "no_matching_people": "No matching employees found.",
        "no_matching_employee_guidance": "No matching employee found; please provide a clearer name or employee ID.",
        "missing_query": "Please provide an HR business question, or pass a query_spec JSON.",
    },
    "Chinese": {
        "no_matching_people": "未找到匹配人员。",
        "no_matching_employee_guidance": "未找到匹配员工；请提供更明确的姓名或员工 ID。",
        "missing_query": "请提供一个 HR 业务问题，或传入 query_spec JSON。",
    },
    "Japanese": {
        "no_matching_people": "該当する社員が見つかりませんでした。",
        "no_matching_employee_guidance": "該当する社員が見つかりませんでした。氏名または社員IDをより明確にご指定ください。",
        "missing_query": "HR業務に関する質問を入力するか、query_spec の JSON を渡してください。",
    },
}


def kb_headers(language: Optional[str]) -> Dict[str, str]:
    return KB_HEADERS.get(language or "", KB_HEADERS[DEFAULT_LANGUAGE])


def kb_string(key: str, language: Optional[str]) -> str:
    table = KB_STRINGS.get(language or "", KB_STRINGS[DEFAULT_LANGUAGE])
    return table.get(key, KB_STRINGS[DEFAULT_LANGUAGE][key])


def hr_string(key: str, language: Optional[str]) -> str:
    table = HR_STRINGS.get(language or "", HR_STRINGS[DEFAULT_LANGUAGE])
    return table.get(key, HR_STRINGS[DEFAULT_LANGUAGE][key])


# HR executor's deterministic formatting (backend/services/agent/tools/builtin/
# business_query_core/hr/executor.py) is called many levels deep from
# run_hr_business_query() without a `language` parameter threaded through
# every function. A request-scoped ContextVar avoids a large, error-prone
# signature change across that call graph; run_hr_business_query() sets it
# once per call and resets it in a `finally`.
_hr_language_ctx: ContextVar[Optional[str]] = ContextVar("hr_fallback_language", default=None)


def set_hr_language(language: Optional[str]):
    return _hr_language_ctx.set(language)


def reset_hr_language(token) -> None:
    _hr_language_ctx.reset(token)


def current_hr_language() -> str:
    return _hr_language_ctx.get() or DEFAULT_LANGUAGE
