"""Generate inference/config/inference.yaml for non-Docker deployments."""

from __future__ import annotations

from pathlib import Path

from vitoom_setup.env_file import backend_url_to_ws_url

LOCAL_INFERENCE_YAML = Path("inference/config/inference.yaml")


def render_local_inference_yaml(env: dict[str, str]) -> str:
    backend = env.get("VITOOM_BACKEND_URL", "").strip() or "http://127.0.0.1:8888"
    ws = env.get("VITOOM_WS_URL", "").strip() or backend_url_to_ws_url(backend)
    secret = env.get("VITOOM_INFERENCE_UPLOAD_AUTH_SECRET", "").strip()
    ttl = env.get("VITOOM_PIPELINE_CACHE_TTL_SECONDS", "0").strip() or "0"
    models_dir = env.get("VITOOM_MODELS_DIR", "resources/models").strip() or "resources/models"
    weights_dir = env.get("VITOOM_WEIGHTS_DIR", "resources/weights").strip() or "resources/weights"
    loras_dir = env.get("VITOOM_LORAS_DIR", "resources/loras").strip() or "resources/loras"
    outputs_dir = env.get("VITOOM_OUTPUTS_DIR", "resources/outputs").strip() or "resources/outputs"

    return f"""# Global inference service configuration
# Generated by scripts/setup_vitoom.py for non-Docker deployments.
# Docker deployments use data/inference/config/inference.yaml (created by container entrypoint).

models_dir: "{models_dir}"
weights_dir: "{weights_dir}"
loras_dir: "{loras_dir}"
outputs_dir: "{outputs_dir}"
pipeline_cache_ttl_seconds: {ttl}

storage:
  default: "server"
  server:
    upload_path: "/api/inference/upload"
    timeout_seconds: 60
    auth:
      secret: "{secret}"
  s3:
    endpoint: null
    region: null
    bucket: ""
    access_key_id: ""
    secret_access_key: ""
    public_base_url: null
  oss:
    endpoint: ""
    bucket: ""
    access_key_id: ""
    access_key_secret: ""
    public_base_url: null

api_base_url: "{backend}"
ws_url: "{ws}"
# Per-service supervisor_url overrides this in {{service_id}}.yaml when needed.
supervisor_url: ""

transport:
  ingresses:
    - type: "ws"
  egresses:
    - type: "ws"
"""


def write_local_inference_yaml(
    env: dict[str, str],
    *,
    repo_root: Path,
    overwrite: bool = False,
) -> Path | None:
    path = repo_root / LOCAL_INFERENCE_YAML
    if path.is_file() and not overwrite:
        return None
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_local_inference_yaml(env), encoding="utf-8")
    return path
