export const samplerOptions: string[] = [
  'DPM++ 2M',
  'DPM++ 2M Karras',
  'DPM++ 2M SDE',
  'DPM++ 2M SDE Karras',
  'DPM++ SDE',
  'DPM++ SDE Karras',
  'DPM2',
  'DPM2 Karras',
  'DPM2 a',
  'DPM2 a Karras',
  'Euler',
  'Euler a',
  'Heun',
  'LMS',
  'LMS Karras',
  'DDPM',
  'DDIM',
  'PNDM',
  'TCD',
  'UniPC',
  'qwen_scheduler_lightning',
]

